### ISSUE TITLE
Can't install on python3

### ISSUE THREAD

**Issue by gwiederhecker** [jkitchin/pycse#20]
```
pip3 install pycse
Collecting pycse
  Using cached pycse-1.51.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/km/38gp_rts2hq1z613vf_2gyx40000gn/T/pip-build-4ojn0412/pycse/setup.py", line 3, in <module>
        from pycse import __version__
      File "/private/var/folders/km/38gp_rts2hq1z613vf_2gyx40000gn/T/pip-build-4ojn0412/pycse/pycse/__init__.py", line 11, in <module>
        from PYCSE import *
    ModuleNotFoundError: No module named 'PYCSE'

**Comment by jkitchin** [comment]
try this:

`pip install pycse==1.6.3`

I don't know why pip is not grabbing the most recent version.
