### ISSUE TITLE
can't install pycse for python3.6

### ISSUE THREAD

**Issue by Infinemen** [jkitchin/pycse#21]
i used "pip install pycse" and "pip install git+git://github.com/jkitchin/pycse" to install pycse, but all failed.
For "pip install pycse" i got 

> Collecting pycse
  Using cached pycse-1.51.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-xy0_8o_0/pycse/setup.py", line 3, in <module>
        from pycse import __version__
      File "/tmp/pip-build-xy0_8o_0/pycse/pycse/__init__.py", line 11, in <module>
        from PYCSE import *
    ModuleNotFoundError: No module named 'PYCSE'
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-xy0_8o_0/pycse/
    ----------------------------------------

For "pip install git+git://github.com/jkitchin/pycse"  , I can install pycse, but can't make it work.

**Comment by jkitchin** [comment]
I finally figured out the problem. I used a bad numbering scheme for a while, e.g. 1.51 instead of 1.5.1. I have pushed a version 2.0 which I believe should solve this problem with "pip install pycse". 

What was the problem with "pip install git+git://github.com/jkitchin/pycse" though?

**Comment by Infinemen** [comment]
@jkitchin  Hi, firstly thank you for your reply and excellent job.  Both methods can install pycse now. But there are another error when i evaluate python blocks in emacs.  It seems like there are something wrong between pycse and quantities. When i evaluated python blocks, i got
>Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/quantities/quantity.py", line 231, in __array_prepare__
    res._dimensionality = p_dict[uf](*objs)
KeyError: <ufunc 'positive'>

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/pycse/__init__.py", line 78, in <module>
    import quantities as u
  File "/usr/lib/python3.6/site-packages/quantities/__init__.py", line 285, in <module>
    from .units import *
  File "/usr/lib/python3.6/site-packages/quantities/units/__init__.py", line 9, in <module>
    from . import acceleration
  File "/usr/lib/python3.6/site-packages/quantities/units/acceleration.py", line 7, in <module>
    from .time import s
  File "/usr/lib/python3.6/site-packages/quantities/units/time.py", line 18, in <module>
    aliases=['milliseconds']
  File "/usr/lib/python3.6/site-packages/quantities/unitquantity.py", line 62, in __new__
    ret._conv_ref = definition._reference
  File "/usr/lib/python3.6/site-packages/quantities/quantity.py", line 139, in _reference
    rq = rq * u._reference**d
  File "/usr/lib/python3.6/site-packages/quantities/unitquantity.py", line 230, in __pow__
    return self.view(Quantity).__pow__(other)
  File "/usr/lib/python3.6/site-packages/quantities/quantity.py", line 88, in g
    return f(self, other, *args)
  File "/usr/lib/python3.6/site-packages/quantities/quantity.py", line 321, in __pow__
    return super(Quantity, self).__pow__(other)
  File "/usr/lib/python3.6/site-packages/quantities/quantity.py", line 236, in __array_prepare__
    """ % uf
ValueError: ufunc <ufunc 'positive'> not supported by quantities
                please file a bug report at https://github.com/python-quantities

**Comment by jkitchin** [comment]
What script are you running? I am not able to reproduce this.

**Comment by Infinemen** [comment]
@jkitchin 
>#+BEGIN_SRC python
  import pycse.orgmode
  import numpy as np
  import matplotlib.pyplot as plt
  plt.xkcd()
  N = 150
  r = 2 * np.random.rand(N)
  theta = 2 * np.pi * np.random.rand(N)
  area = 200 * r**2 * np.random.rand(N)
  colors = theta
  ax = plt.subplot(111, polar=True)
  c = plt.scatter(theta, r, c=colors, s=area, cmap=plt.cm.hsv)
  c.set_alpha(0.75)
  print(plt.savefig('test.png'))
>#+END_SRC

**Comment by jkitchin** [comment]
That script works fine for me. Do you know what version of quantities you are running? It looks like the problem is there, not in pycse.

**Comment by Infinemen** [comment]
@jkitchin My quantities version is 0.11.1. By the way what version should I use? Thanks  a lot!

**Comment by jkitchin** [comment]
I was using 0.10.1 I think. I upgraded and now it says 0+unknown, but I think it is 0.11.1. It still worked.  I don't know why you would see something different.
